default:
  experiment_name: 1sec_random
  plot_path: /ac-project/nprzybylski/window/plots/
sweep:
  file_idxs:
  - 1396
  - 502
  - 1418
  - 990
  - 1420
  - 1823
  - 1408
  - 1296
  - 1402
  - 144
  n_files: 6
  random_pick: True
  width_per_step:
    hi: 2500
    lo: 2500
    step: 500
  window_width:
    hi: 250000
    lo: 5000
    step: 5000
