---
  default:
    plot_path: './plots/'
    experiment_name: 'a_test'

  sweep:
    random_pick: False
    n_files: 6
    file_paths:
      - 'full/horizontal-misalignment/0.5mm/32.3584.csv'
      - 'full/imbalance/20g/41.5744.csv'
      - 'full/normal/29.4912.csv'
      - 'full/overhang/ball_fault/0g/61.44.csv'
      - 'full/underhang/ball_fault/0g/56.5248.csv'
      - 'full/vertical-misalignment/0.63mm/18.8416.csv'
    width_per_step:
      lo: 10000
      hi: 10000
      step: 500
    window_width:
      lo: 45000
      hi: 55000
      step: 5000
