default:
  experiment_name: all_vertical_misalignments_2500_250k_5sec
  plot_path: /ac-project/nprzybylski/window/plots/
sweep:
  file_idxs:
  - 194
  - 256
  - 7
  - 84
  - 9
  - 212
  - 134
  - 214
  - 60
  - 12
  - 10
  - 0
  - 285
  - 30
  - 222
  - 228
  - 102
  - 249
  - 11
  - 145
  - 171
  - 209
  - 276
  - 6
  - 124
  - 34
  - 104
  - 46
  - 260
  - 130
  - 300
  - 246
  - 226
  - 267
  - 74
  - 294
  - 258
  - 69
  - 144
  - 62
  - 133
  - 33
  - 14
  - 284
  - 43
  - 257
  - 151
  - 50
  - 16
  - 5
  - 154
  - 218
  - 52
  - 13
  - 115
  - 48
  - 275
  - 79
  - 229
  n_files: 4
  random_pick: false
  width_per_step:
    hi: 2500
    lo: 2500
    step: 500
  window_width:
    hi: 250000
    lo: 5000
    step: 5000
