default:
  experiment_name: all_horizontal_misalignments
  plot_path: /ac-project/nprzybylski/window/plots/
sweep:
  file_idxs:
  - 1221
  - 1270
  - 1370
  - 1204
  - 1381
  - 1331
  - 1224
  - 1247
  - 1251
  - 1387
  - 1330
  - 1386
  - 1257
  - 1351
  - 1363
  n_files: 10
  random_pick: false
  width_per_step:
    hi: 10000
    lo: 10000
    step: 500
  window_width:
    hi: 250000
    lo: 250000
    step: 500
