default:
  experiment_name: all_normals_250000
  plot_path: /ac-project/nprzybylski/window/plots/
sweep:
  file_idxs:
  - 1420
  - 1402
  - 1396
  - 1399
  - 1398
  - 1429
  - 1416
  n_files: 10
  random_pick: false
  width_per_step:
    hi: 10000
    lo: 10000
    step: 500
  window_width:
    hi: 250000
    lo: 250000
    step: 500
