default:
  experiment_name: all_normals_2500_250k_5sec
  plot_path: /ac-project/nprzybylski/window/plots/
sweep:
  file_idxs:
  - 1420
  - 1402
  - 1396
  - 1399
  - 1398
  - 1429
  - 1416
  - 1412
  - 1417
  - 1390
  - 1418
  - 1395
  - 1408
  - 1410
  - 1394
  n_files: 4
  random_pick: false
  width_per_step:
    hi: 2500
    lo: 2500
    step: 500
  window_width:
    hi: 250000
    lo: 5000
    step: 5000
