default:
  experiment_name: all_vertical_misalignments
  plot_path: /Users/nrprzybyl/ML/MAFAULDA/window/plots/
sweep:
  file_idxs:
  - 171
  - 276
  - 228
  - 275
  - 43
  - 267
  - 0
  - 218
  - 209
  - 222
  - 60
  - 294
  - 226
  - 79
  - 34
  - 300
  - 246
  - 7
  - 14
  - 249
  - 16
  - 13
  - 284
  - 12
  - 212
  - 134
  - 144
  - 69
  n_files: 10
  random_pick: false
  width_per_step:
    hi: 10000
    lo: 10000
    step: 500
  window_width:
    hi: 50000
    lo: 1000
    step: 5000
