---
  default:
    plot_path: '/ac-project/nprzybylski/window/plots/'
    experiment_name: 'test_new_workflow1'

  sweep:
    random_pick: True
    n_files: 4
    file_idxs:
      - 1396
      - 502
      - 1418
      - 990
        #- 1420
        #- 1823
        #- 1408
        #- 1296
        #- 1402
        #- 144
    width_per_step:
      lo: 10000
      hi: 10000
      step: 500
    window_width:
      lo: 1000
      hi: 250000
      step: 1000
