---
  default:
    plot_path: '/Users/nrprzybyl/ML/MAFAULDA/window/plots/'
    experiment_name: 'test3_fixed'

  sweep:
    random_pick: False
    n_files: 10
    file_idxs:
      - 1396
      - 502
      - 1418
      - 990
        #- 1420
        #- 1823
        #- 1408
        #- 1296
        #- 1402
        #- 144
    width_per_step:
      lo: 10000
      hi: 10000
      step: 500
    window_width:
      lo: 5000
      hi: 100000
      step: 15000
